const defaultColors = require('tailwindcss/colors');
const defaultTheme = require('tailwindcss/defaultTheme');

const { inherit, current, transparent } = defaultColors;
const { borderRadius } = defaultTheme;

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}'
  ],
  future: {
    hoverOnlyWhenSupported: true
  },
  darkMode: 'class',
  theme: {
    fontFamily: {
      primary: '"Poppins", sans-serif',
      secondary: '"Inter", sans-serif'
    },
    colors: {
      inherit,
      current,
      transparent,
      primary: 'var(--primary)',
      'primary-0': 'var(--primary-0)',
      'primary-5': 'var(--primary-5)',
      'primary-10': 'var(--primary-10)',
      'primary-15': 'var(--primary-15)',
      'primary-20': 'var(--primary-20)',
      'primary-25': 'var(--primary-25)',
      'primary-30': 'var(--primary-30)',
      'primary-35': 'var(--primary-35)',
      'primary-40': 'var(--primary-40)',
      'primary-45': 'var(--primary-45)',
      'primary-50': 'var(--primary-50)',
      'primary-55': 'var(--primary-55)',
      'primary-60': 'var(--primary-60)',
      'primary-65': 'var(--primary-65)',
      'primary-70': 'var(--primary-70)',
      'primary-75': 'var(--primary-75)',
      'primary-80': 'var(--primary-80)',
      'primary-85': 'var(--primary-85)',
      'primary-90': 'var(--primary-90)',
      'primary-95': 'var(--primary-95)',
      'primary-98': 'var(--primary-98)',
      'primary-99': 'var(--primary-99)',
      'primary-100': 'var(--primary-100)',
      secondary: 'var(--secondary)',
      'secondary-0': 'var(--secondary-0)',
      'secondary-5': 'var(--secondary-5)',
      'secondary-10': 'var(--secondary-10)',
      'secondary-15': 'var(--secondary-15)',
      'secondary-20': 'var(--secondary-20)',
      'secondary-25': 'var(--secondary-25)',
      'secondary-30': 'var(--secondary-30)',
      'secondary-35': 'var(--secondary-35)',
      'secondary-40': 'var(--secondary-40)',
      'secondary-45': 'var(--secondary-45)',
      'secondary-50': 'var(--secondary-50)',
      'secondary-55': 'var(--secondary-55)',
      'secondary-60': 'var(--secondary-60)',
      'secondary-65': 'var(--secondary-65)',
      'secondary-70': 'var(--secondary-70)',
      'secondary-75': 'var(--secondary-75)',
      'secondary-80': 'var(--secondary-80)',
      'secondary-85': 'var(--secondary-85)',
      'secondary-90': 'var(--secondary-90)',
      'secondary-95': 'var(--secondary-95)',
      'secondary-98': 'var(--secondary-98)',
      'secondary-99': 'var(--secondary-99)',
      'secondary-100': 'var(--secondary-100)',
      tertiary: 'var(--tertiary)',
      'tertiary-0': 'var(--tertiary-0)',
      'tertiary-5': 'var(--tertiary-5)',
      'tertiary-10': 'var(--tertiary-10)',
      'tertiary-15': 'var(--tertiary-15)',
      'tertiary-20': 'var(--tertiary-20)',
      'tertiary-25': 'var(--tertiary-25)',
      'tertiary-30': 'var(--tertiary-30)',
      'tertiary-35': 'var(--tertiary-35)',
      'tertiary-40': 'var(--tertiary-40)',
      'tertiary-45': 'var(--tertiary-45)',
      'tertiary-50': 'var(--tertiary-50)',
      'tertiary-55': 'var(--tertiary-55)',
      'tertiary-60': 'var(--tertiary-60)',
      'tertiary-65': 'var(--tertiary-65)',
      'tertiary-70': 'var(--tertiary-70)',
      'tertiary-75': 'var(--tertiary-75)',
      'tertiary-80': 'var(--tertiary-80)',
      'tertiary-85': 'var(--tertiary-85)',
      'tertiary-90': 'var(--tertiary-90)',
      'tertiary-95': 'var(--tertiary-95)',
      'tertiary-98': 'var(--tertiary-98)',
      'tertiary-99': 'var(--tertiary-99)',
      'tertiary-100': 'var(--tertiary-100)',
      neutral: 'var(--neutral)',
      'neutral-0': 'var(--neutral-0)',
      'neutral-5': 'var(--neutral-5)',
      'neutral-10': 'var(--neutral-10)',
      'neutral-15': 'var(--neutral-15)',
      'neutral-20': 'var(--neutral-20)',
      'neutral-25': 'var(--neutral-25)',
      'neutral-30': 'var(--neutral-30)',
      'neutral-35': 'var(--neutral-35)',
      'neutral-40': 'var(--neutral-40)',
      'neutral-45': 'var(--neutral-45)',
      'neutral-50': 'var(--neutral-50)',
      'neutral-55': 'var(--neutral-55)',
      'neutral-60': 'var(--neutral-60)',
      'neutral-65': 'var(--neutral-65)',
      'neutral-70': 'var(--neutral-70)',
      'neutral-75': 'var(--neutral-75)',
      'neutral-80': 'var(--neutral-80)',
      'neutral-85': 'var(--neutral-85)',
      'neutral-90': 'var(--neutral-90)',
      'neutral-95': 'var(--neutral-95)',
      'neutral-98': 'var(--neutral-98)',
      'neutral-99': 'var(--neutral-99)',
      'neutral-100': 'var(--neutral-100)',
      'neutral-variant': 'var(--neutral-variant)',
      'neutral-variant-0': 'var(--neutral-variant-0)',
      'neutral-variant-5': 'var(--neutral-variant-5)',
      'neutral-variant-10': 'var(--neutral-variant-10)',
      'neutral-variant-15': 'var(--neutral-variant-15)',
      'neutral-variant-20': 'var(--neutral-variant-20)',
      'neutral-variant-25': 'var(--neutral-variant-25)',
      'neutral-variant-30': 'var(--neutral-variant-30)',
      'neutral-variant-35': 'var(--neutral-variant-35)',
      'neutral-variant-40': 'var(--neutral-variant-40)',
      'neutral-variant-45': 'var(--neutral-variant-45)',
      'neutral-variant-50': 'var(--neutral-variant-50)',
      'neutral-variant-55': 'var(--neutral-variant-55)',
      'neutral-variant-60': 'var(--neutral-variant-60)',
      'neutral-variant-65': 'var(--neutral-variant-65)',
      'neutral-variant-70': 'var(--neutral-variant-70)',
      'neutral-variant-75': 'var(--neutral-variant-75)',
      'neutral-variant-80': 'var(--neutral-variant-80)',
      'neutral-variant-85': 'var(--neutral-variant-85)',
      'neutral-variant-90': 'var(--neutral-variant-90)',
      'neutral-variant-95': 'var(--neutral-variant-95)',
      'neutral-variant-98': 'var(--neutral-variant-98)',
      'neutral-variant-99': 'var(--neutral-variant-99)',
      'neutral-variant-100': 'var(--neutral-variant-100)',
      error: 'var(--error)',
      'error-0': 'var(--error-0)',
      'error-5': 'var(--error-5)',
      'error-10': 'var(--error-10)',
      'error-15': 'var(--error-15)',
      'error-20': 'var(--error-20)',
      'error-25': 'var(--error-25)',
      'error-30': 'var(--error-30)',
      'error-35': 'var(--error-35)',
      'error-40': 'var(--error-40)',
      'error-45': 'var(--error-45)',
      'error-50': 'var(--error-50)',
      'error-55': 'var(--error-55)',
      'error-60': 'var(--error-60)',
      'error-65': 'var(--error-65)',
      'error-70': 'var(--error-70)',
      'error-75': 'var(--error-75)',
      'error-80': 'var(--error-80)',
      'error-85': 'var(--error-85)',
      'error-90': 'var(--error-90)',
      'error-95': 'var(--error-95)',
      'error-98': 'var(--error-98)',
      'error-99': 'var(--error-99)',
      'error-100': 'var(--error-100)',
      'surface-1': 'var(--surface-1)',
      'surface-2': 'var(--surface-2)',
      'surface-3': 'var(--surface-3)',
      'surface-4': 'var(--surface-4)',
      'surface-5': 'var(--surface-5)',
      disabled: 'var(--disabled)',
      'on-primary': 'var(--on-primary)',
      'primary-container': 'var(--primary-container)',
      'on-primary-container': 'var(--on-primary-container)',
      'on-secondary': 'var(--on-secondary)',
      'secondary-container': 'var(--secondary-container)',
      'on-secondary-container': 'var(--on-secondary-container)',
      'on-tertiary': 'var(--on-tertiary)',
      'tertiary-container': 'var(--tertiary-container)',
      'on-tertiary-container': 'var(--on-tertiary-container)',
      'on-error': 'var(--on-error)',
      'error-container': 'var(--error-container)',
      'on-error-container': 'var(--on-error-container)',
      background: 'var(--background)',
      'on-background': 'var(--on-background)',
      surface: 'var(--surface)',
      'on-surface': 'var(--on-surface)',
      'surface-variant': 'var(--surface-variant)',
      'on-surface-variant': 'var(--on-surface-variant)',
      outline: 'var(--outline)',
      'outline-variant': 'var(--outline-variant)',
      shadow: 'var(--shadow)',
      scrim: 'var(--scrim)',
      'inverse-surface': 'var(--inverse-surface)',
      'inverse-on-surface': 'var(--inverse-on-surface)',
      'inverse-primary': 'var(--inverse-primary)',
      'primary-text': 'var(--on-surface)',
      'secondary-text': 'var(--on-surface-variant)',
      'disabled-text': 'var(--disabled)',
      'scrollbar-thumb': 'var(--scrollbar-thumb)',
      'scrollbar-thumb-hover': 'var(--scrollbar-thumb-hover)'
    },
    screens: {
      xs: '400px',
      sm: '600px',
      md: '900px',
      lg: '1200px',
      xl: '1536px'
    },
    borderRadius: {
      none: borderRadius.none,
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '32px',
      xl: '64px',
      full: borderRadius.full
    },
    extend: {}
  },
  plugins: []
};
